import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import NavBar from "@/components/navBar/navBar";

export const metadata: Metadata = {
  title: "MARKET MARKET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
